[package]
authors = ["blackbeam <aikorsky@gmail.com>"]
name = "mysql_common"
description = "MySql protocol primitives"
license = "MIT/Apache-2.0"
homepage = "https://github.com/blackbeam/rust_mysql_common"
documentation = "https://docs.rs/mysql_common"
repository = "https://github.com/blackbeam/rust_mysql_common"
keywords = ["mysql", "database"]
categories = ["database"]

# * Invoke `cargo readme > README.md` if relevant!
version = "0.29.2"


edition = "2018"
exclude = ["/lib", "/proptest-regressions", "/test-data", "/wrapper.cc", "/wrapper.hh"]

[badges]
travis-ci = { repository = "blackbeam/rust_mysql_common" }

[dependencies]
base64 = "0.13"
bigdecimal = { version = "0.2", features = ["serde"], optional = true }
bigdecimal03 = { package = "bigdecimal", version = "0.3", optional = true }
bitflags = "1"
bitvec = "1.0.0"
byteorder = "1"
bytes = "1.0"
chrono = { version = "0.4.19", features = ["serde"], optional = true }
crc32fast = "1.2"
flate2 = { version = "1.0", default-features = false }
frunk = { version = "0.4", optional = true }
lazy_static = "1"
lexical = "6.0.1"
num-bigint = { version = "0.4" }
num-traits = { version = "0.2", features = ["i128"] }
rand = "0.8.3"
regex = "1.5.5"
rust_decimal = { version = "1.0", optional = true }
sha1 = "0.10.0"
sha2 = "0.10.0"
smallvec = { version = "1.6.1", features = ["union", "write"] }
thiserror = "1.0.24"
time = { version = "0.2", default-features = false, features = ["std"], optional = true }
time03 = { package = "time", version = "0.3", default-features = false, features = ["parsing"], optional = true }
uuid = { version = "1", optional = true }
saturating = "0.1"
serde = "1"
serde_json = "1"
zstd = "0.12.4"
[dev-dependencies]
proptest = "1.0"

[build-dependencies]
bindgen = { version = "0.59.2", default-features = false, features = ["runtime"] }
cc = "1.0.54"
cmake = "0.1.44"
subprocess = "0.2.4"

[profile.bench]
debug = true

[features]
default = [
    "flate2/zlib",
    "bigdecimal03",
    "rust_decimal",
    "time03",
    "uuid",
    "frunk",
]
test = []
nightly = ["test"]
